# Generated by Django 2.1.7 on 2019-04-11 17:35

from django.db import migrations, models
import django.db.models.deletion
import login.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='achievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('abstract', models.CharField(max_length=255)),
                ('keywords', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='achievement_author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iscorr', models.BooleanField()),
                ('isfirst', models.BooleanField()),
                ('order', models.IntegerField()),
                ('achievement_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.achievement')),
            ],
        ),
        migrations.CreateModel(
            name='author',
            fields=[
                ('aid', models.BigAutoField(primary_key=True, serialize=False)),
                ('aname', models.CharField(max_length=255)),
                ('amail', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('series', models.CharField(max_length=255, null=True)),
                ('btype', models.CharField(max_length=255)),
                ('isbn', models.CharField(max_length=255)),
                ('edit', models.CharField(max_length=255)),
                ('pubdate', models.DateField()),
                ('publisher', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('total_words', models.IntegerField()),
                ('lang', models.CharField(max_length=255)),
                ('achievement_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.achievement')),
            ],
        ),
        migrations.CreateModel(
            name='chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('book_title', models.CharField(max_length=255)),
                ('isbn', models.CharField(max_length=255, null=True)),
                ('pages', models.CharField(max_length=255, null=True)),
                ('pubdate', models.DateField()),
                ('edit', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('publisher', models.CharField(max_length=255)),
                ('achievement_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.achievement')),
            ],
        ),
        migrations.CreateModel(
            name='college',
            fields=[
                ('coid', models.BigAutoField(primary_key=True, serialize=False)),
                ('coname', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='company',
            fields=[
                ('cid', models.BigAutoField(primary_key=True, serialize=False)),
                ('dename', models.CharField(max_length=255)),
                ('coid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.college')),
            ],
        ),
        migrations.CreateModel(
            name='conference_paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctype', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('conference_name', models.CharField(max_length=255)),
                ('organizer', models.CharField(max_length=255, null=True)),
                ('country', models.CharField(max_length=255)),
                ('pubdate', models.DateField(null=True)),
                ('proceeding', models.CharField(max_length=255, null=True)),
                ('begin_date', models.DateField()),
                ('end_date', models.DateField()),
                ('pages', models.CharField(max_length=255, null=True)),
                ('indexed', models.CharField(max_length=255, null=True)),
                ('doi', models.CharField(max_length=255, null=True)),
                ('achievement_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.achievement')),
            ],
        ),
        migrations.CreateModel(
            name='degree_paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('degree', models.CharField(max_length=255)),
                ('pubdate', models.DateField()),
                ('institution', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('doi', models.CharField(max_length=255, null=True)),
                ('achievement_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.achievement')),
            ],
        ),
        migrations.CreateModel(
            name='journal_paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('jname', models.CharField(max_length=255)),
                ('status', models.BooleanField()),
                ('pubdate', models.DateField()),
                ('volume', models.CharField(max_length=255, null=True)),
                ('issue', models.CharField(max_length=255, null=True)),
                ('pages', models.CharField(max_length=255, null=True)),
                ('indexed', models.CharField(max_length=255, null=True)),
                ('doi', models.CharField(max_length=255, null=True)),
                ('achievement_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.achievement')),
            ],
        ),
        migrations.CreateModel(
            name='patent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=255)),
                ('ptype', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('status', models.BooleanField()),
                ('number', models.CharField(max_length=255)),
                ('ipc', models.CharField(max_length=255, null=True)),
                ('cpc', models.CharField(max_length=255, null=True)),
                ('owner', models.CharField(max_length=255, null=True)),
                ('aptime', models.DateField()),
                ('pubnumber', models.CharField(max_length=255, null=True)),
                ('ssue_begin', models.DateField(null=True)),
                ('ssue_end', models.DateField(null=True)),
                ('transition', models.CharField(max_length=255, null=True)),
                ('price', models.FloatField(null=True)),
                ('achievement_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.achievement')),
            ],
        ),
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_id', models.CharField(max_length=255)),
                ('pro_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='project_achievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('achievement_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.achievement')),
                ('pro_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.project')),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('uid', models.BigAutoField(primary_key=True, serialize=False)),
                ('uaccount', models.CharField(max_length=255, unique=True)),
                ('unamech', models.CharField(max_length=255, null=True)),
                ('unameen', models.CharField(max_length=255)),
                ('umail', models.CharField(max_length=255, unique=True)),
                ('upassword', models.CharField(max_length=255)),
                ('uphone', login.models.MyCharField(max_length=11)),
                ('uall', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='author',
            name='cid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.company'),
        ),
        migrations.AddField(
            model_name='achievement_author',
            name='author_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.author'),
        ),
    ]
